// packages/svelte/src/QRX.svelte
<script lang="ts">
  import { getSVGData, type Options } from '@qr-x/core'
  import type { SVGAttributes } from 'svelte/elements'
  import Group from './Group.svelte'

  type Props = SVGAttributes<never> & Options

  interface $$Props extends Props {}

  export let data: Options['data']
  export let level: Options['level'] = undefined
  export let image: Options['image'] = undefined
  export let shapes: Options['shapes'] = undefined
  export let gradient: Options['gradient'] = undefined
  export let fillImage: Options['fillImage'] = undefined

  const {
    ids,
    fills,
    paths,
    length,
    markers,
    gradient: _gradient,
    eyeItems,
    isMasked,
  } = getSVGData({
    data,
    level,
    image,
    shapes,
    gradient,
    fillImage,
  })
</script>

<svg width="100%" {...$$restProps} viewBox={`0 0 ${length} ${length}`}>
  {#if isMasked}
    <g>
      <mask id="mask"> <Group {ids} {paths} {fills} {markers} {eyeItems} /></mask>
      <rect x="0" y="0" width="100%" height="100%" fill={fills.rect} mask="url('#mask')" />
    </g>
  {:else}
    <Group {ids} {paths} {fills} {markers} {eyeItems} />
  {/if}

  <defs>
    {#each eyeItems as item}
      <path id={ids[item]} d={paths[item]} />
    {/each}

    {#if _gradient}
      <svelte:element this={_gradient.isLinearGradient ? 'linearGradient' : 'radialGradient'} {..._gradient.attributes}>
        {#each _gradient.colors as { color, offset }}
          <stop {offset} stop-color={color} />
        {/each}
      </svelte:element>
    {:else if fillImage}
      <pattern id={ids.image} patternUnits="userSpaceOnUse" width="100%" height="100%">
        <image href={fillImage} x="0" y="0" width="100%" height="100%" preserveAspectRatio="xMidYMid slice" />
      </pattern>
    {/if}
  </defs>
</svg>

// packages/vue/src/QRX.vue
<script setup lang="ts">
import G from './G.vue'
import { SVGAttributes } from 'vue'
import { Options, getSVGData } from '@qr-x/core'

interface Props extends Options {}

interface Props extends SVGAttributes {}

const { data, level, image, shapes, fillImage, gradient: $gradient, ...rest } = defineProps<Props>()

const { ids, fills, paths, length, markers, gradient, eyeItems, isMasked } = getSVGData({
  data: data,
  level: level,
  shapes: shapes,
  gradient: $gradient,
  fillImage: fillImage,
})
</script>

<template>
  <svg v-bind="rest" width="100%" :viewBox="`0 0 ${length} ${length}`">
    <g v-if="isMasked">
      <mask id="mask">
        <G :ids="ids" :paths="paths" :fills="fills" :markers="markers" :eyeItems="eyeItems" />
      </mask>
      <rect x="0" y="0" width="100%" height="100%" :fill="fills.rect" mask="url('#mask')" />
    </g>
    <G v-else :ids="ids" :paths="paths" :fills="fills" :markers="markers" :eyeItems="eyeItems" />

    <defs>
      <path v-for="item in eyeItems" :key="item" :id="ids[item]" :d="paths[item]" />

      <component
        v-if="gradient"
        :is="gradient.isLinearGradient ? 'linearGradient' : 'radialGradient'"
        v-bind="gradient.attributes"
      >
        <stop v-for="({ color, offset }, index) in gradient.colors" :key="index" :offset="offset" :stop-color="color" />
      </component>

      <pattern v-if="fillImage" :id="ids.image" patternUnits="userSpaceOnUse" width="100%" height="100%">
        <image
          x="0"
          y="0"
          width="100%"
          height="100%"
          :href="fillImage"
          :xlinkHref="fillImage"
          preserveAspectRatio="xMidYMid slice"
        />
      </pattern>
    </defs>
  </svg>
</template>
